### ISSUE TITLE
linting

### ISSUE THREAD

**Issue by larshp** [MindsetConsulting/gateway-error-reporting#5]
Hi,
DDLX objects are now recognized correctly, https://github.com/larshp/abaplint/commit/3b1fb0d3cad7370e8caa788d1f14d110162ad1b9

I recommend changing the line https://github.com/MindsetConsulting/gateway-error-reporting/blob/master/abaplint.json#L3 to the target version, eg "v740sp08"

**Comment by esjewett** [comment]
@larshp Thanks - that's great!
